[package]
name = "pajoniiir-media-fat32"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
embedded-sdmmc.workspace = true
pajoniiir-media-block.workspace = true
pajoniiir-media-fs.workspace = true
pajoniiir-media-partition.workspace = true
pajoniiir-media-session.workspace = true
