#!/usr/bin/env python3
"""Finalize deterministic M1-ELEC-B2 outputs before structural/KiCad validation.

This script contains only contract-normalization fixes discovered by the first full
post-migration structural audit.  It is intentionally idempotent.
"""
from __future__ import annotations

from pathlib import Path
import json
import re

B = Path(__file__).resolve().parents[1]
P10 = B / "10_DISPLAY_MIPI.kicad_sch"
P11 = B / "11_TOUCH_GT911.kicad_sch"
P14 = B / "14_TEST_MONITORING.kicad_sch"
VAL = B / "tools/validate_schematic_structure.py"
MIG = B / "tools/migrate_display_dsi506_b2.py"
GATES = B / "mechanical_gates.json"
FD = B / "final_display_module.json"
DC = B / "display_connector_b1.json"


def sexpr_at(text: str, start: int) -> tuple[str, int]:
    depth = 0
    in_string = False
    escaped = False
    begun = False
    for i in range(start, len(text)):
        ch = text[i]
        if in_string:
            if escaped:
                escaped = False
                continue
            if ch == "\\":
                escaped = True
                continue
            if ch == '"':
                in_string = False
            continue
        if ch == '"':
            in_string = True
            continue
        if ch == "(":
            depth += 1
            begun = True
        elif ch == ")":
            depth -= 1
            if begun and depth == 0:
                return text[start : i + 1], i + 1
    raise ValueError(f"unterminated S-expression at {start}")


def left_justify_top_text(path: Path) -> None:
    text = path.read_text()
    needle = "\n  (text "
    pos = 0
    replacements: list[tuple[int, int, str]] = []
    while True:
        found = text.find(needle, pos)
        if found < 0:
            break
        start = found + 1
        block, end = sexpr_at(text, start)
        if "(justify left)" not in block:
            # Engineering notes generated by B2 all use this standard effects form.
            old = "(effects (font (size 1.27 1.27)))"
            if old not in block:
                raise SystemExit(f"{path.name}: top-level note has unexpected effects syntax")
            block = block.replace(old, "(effects (font (size 1.27 1.27)) (justify left))", 1)
            replacements.append((start, end, block))
        pos = end
    for start, end, block in reversed(replacements):
        text = text[:start] + block + text[end:]
    path.write_text(text)


def recursive_replace(value, old: str, new: str):
    if isinstance(value, str):
        return value.replace(old, new)
    if isinstance(value, list):
        return [recursive_replace(v, old, new) for v in value]
    if isinstance(value, dict):
        return {k: recursive_replace(v, old, new) for k, v in value.items()}
    return value


def normalize_j10() -> None:
    text = P10.read_text()
    if "J10" not in text:
        if "J8" not in text:
            raise SystemExit("10_DISPLAY_MIPI: neither J8 nor J10 exists after B2 migration")
        text = text.replace("J8", "J10")
        P10.write_text(text)

    for path in (GATES, FD, DC):
        data = json.loads(path.read_text())
        data = recursive_replace(data, "J8", "J10")
        path.write_text(json.dumps(data, indent=2) + "\n")


def normalize_test_monitoring_i2c() -> None:
    text = P14.read_text()
    text = text.replace('"I2C_SDA"', '"DISPLAY_I2C_SDA"')
    text = text.replace('"I2C_SCL"', '"DISPLAY_I2C_SCL"')
    P14.write_text(text)


def normalize_validator() -> None:
    text = VAL.read_text()
    text = text.replace('final DSI506 J8 connector missing', 'final DSI506 J10 connector missing')
    text = text.replace('(property "Reference" "J8"', '(property "Reference" "J10"')

    old = '''            expected_unit2 = {
                "TOUCH_RST": "GPIO3",
                "TOUCH_INT": "GPIO4",
                "LCD_RST": "GPIO5",
                "LCD_TE": "GPIO6",
                "I2C_SDA": "GPIO7",
                "I2C_SCL": "GPIO8",'''
    new = '''            expected_unit2 = {
                "DISPLAY_I2C_SDA": "GPIO7",
                "DISPLAY_I2C_SCL": "GPIO8",'''
    if old in text:
        text = text.replace(old, new, 1)
    elif '"DISPLAY_I2C_SDA": "GPIO7"' not in text:
        raise SystemExit("validator: expected unit-2 mapping preamble not found")

    old = '''                    "GPIO0", "GPIO1", "GPIO2",
                    "GPIO9", "GPIO10", "GPIO11", "GPIO12", "GPIO13",'''
    new = '''                    "GPIO0", "GPIO1", "GPIO2",
                    "GPIO3", "GPIO4", "GPIO5", "GPIO6",
                    "GPIO9", "GPIO10", "GPIO11", "GPIO12", "GPIO13",
                    "GPIO23/ADC1_CHANNEL7",'''
    if old in text:
        text = text.replace(old, new, 1)
    elif '"GPIO23/ADC1_CHANNEL7"' not in text.split("unused_unit2 =", 1)[1].split("}", 1)[0]:
        raise SystemExit("validator: unused unit-2 set insertion point not found")

    # The generated B2 display contract must use J10 in all user-facing messages.
    text = text.replace("J8 connector", "J10 connector")
    VAL.write_text(text)


def normalize_migrator_source_for_reproducibility() -> None:
    text = MIG.read_text()
    # J8 was discovered to collide with 13_DEBUG_SERVICE; J10 is unallocated.
    text = text.replace("J8", "J10")
    # Future migrations must emit left-justified notes directly.
    note_expr = "(exclude_from_sim no) (at 145 {135+i*5} 0) {EFF}"
    note_repl = "(exclude_from_sim no) (at 145 {135+i*5} 0) (effects (font (size 1.27 1.27)) (justify left))"
    text = text.replace(note_expr, note_repl)
    # Stub notes also need the same review-layout invariant.
    text = text.replace("{EFF} (uuid \"{U('stub1')}\")", "(effects (font (size 1.27 1.27)) (justify left)) (uuid \"{U('stub1')}\")")
    text = text.replace("{EFF} (uuid \"{U('stub2')}\")", "(effects (font (size 1.27 1.27)) (justify left)) (uuid \"{U('stub2')}\")")
    text = text.replace("{EFF} (uuid \"{U('stub3')}\")", "(effects (font (size 1.27 1.27)) (justify left)) (uuid \"{U('stub3')}\")")
    MIG.write_text(text)


def assert_contracts() -> None:
    p10 = P10.read_text()
    p11 = P11.read_text()
    p14 = P14.read_text()
    val = VAL.read_text()
    if '(property "Reference" "J10"' not in p10:
        raise SystemExit("final J10 connector not instantiated")
    if '(property "Reference" "J8"' in p10:
        raise SystemExit("stale J8 connector reference remains in display sheet")
    if '"I2C_SDA"' in p14 or '"I2C_SCL"' in p14:
        raise SystemExit("14_TEST_MONITORING still exports legacy I2C names")
    for path, text in ((P10, p10), (P11, p11)):
        for match in re.finditer(r'\n  \(text ', text):
            block, _ = sexpr_at(text, match.start() + 1)
            if "(justify left)" not in block:
                raise SystemExit(f"{path.name}: non-left-justified engineering note remains")
    for required in (
        '"DISPLAY_I2C_SDA": "GPIO7"',
        '"DISPLAY_I2C_SCL": "GPIO8"',
        '"GPIO3", "GPIO4", "GPIO5", "GPIO6"',
        '"GPIO23/ADC1_CHANNEL7"',
    ):
        if required not in val:
            raise SystemExit(f"validator missing B2 GPIO contract token: {required}")


def main() -> None:
    normalize_j10()
    left_justify_top_text(P10)
    left_justify_top_text(P11)
    normalize_test_monitoring_i2c()
    normalize_validator()
    normalize_migrator_source_for_reproducibility()
    assert_contracts()
    print("PASS: B2 output finalization complete")
    print("PASS: J10 unique; display I2C/test-monitoring aligned; released GPIOs explicit NC")


if __name__ == "__main__":
    main()
