[workspace]
members = [
    "apps/desktop-simulator",
    "crates/pajoniiir-core",
    "crates/pajoniiir-controller-core",
    "crates/pajoniiir-ui-model",
    "crates/pajoniiir-waveform",
]
default-members = [
    "apps/desktop-simulator",
    "crates/pajoniiir-core",
    "crates/pajoniiir-controller-core",
    "crates/pajoniiir-ui-model",
    "crates/pajoniiir-waveform",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.95.0"
publish = false

[workspace.dependencies]
embedded-graphics = { version = "=0.8.2", default-features = false }
slint = { version = "=1.18.1", default-features = false, features = ["std", "backend-winit", "renderer-software", "compat-1-18"] }
slint-build = { version = "=1.18.1" }

pajoniiir-core = { path = "crates/pajoniiir-core" }
pajoniiir-controller-core = { path = "crates/pajoniiir-controller-core" }
pajoniiir-ui-model = { path = "crates/pajoniiir-ui-model" }
pajoniiir-waveform = { path = "crates/pajoniiir-waveform" }
